AWSTemplateFormatVersion: '2010-09-09'
Description: 3 public subnets and 3 intra subnets
Parameters:
  Env:
    Description: Enter the environment. (prd/dev/stg)
    Type: String
    Default: dev
    AllowedValues:
    - dev
    - prd
    - stg
Resources:
  VPC:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.ap-northeast-1.amazonaws.com/cfn-20201003-225832-39f581a3-b5dc-4e57-bafb-e4028e6ceff7/2bd6dbfa6831b45e7dbf9f45917ba28a.template
      Parameters:
        Env:
          Ref: Env
  PublicSubnets:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.ap-northeast-1.amazonaws.com/cfn-20201003-225832-39f581a3-b5dc-4e57-bafb-e4028e6ceff7/ed98b485efbeaaae1a3849a4794bb877.template
      Parameters:
        Env:
          Ref: Env
        VpcId:
          Fn::GetAtt:
          - VPC
          - Outputs.VpcId
  IntraSubnets:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.ap-northeast-1.amazonaws.com/cfn-20201003-225832-39f581a3-b5dc-4e57-bafb-e4028e6ceff7/54f0771423bb63e32b4ad13814f8d1d2.template
      Parameters:
        Env:
          Ref: Env
        VpcId:
          Fn::GetAtt:
          - VPC
          - Outputs.VpcId
Outputs:
  DefaultSecurityGroupId:
    Value:
      Fn::GetAtt:
      - VPC
      - Outputs.DefaultSecurityGroupId
